package tillerino.tillerinobot;

import static org.junit.Assume.assumeTrue;

import org.junit.Test;
import org.tillerino.ppaddict.util.TillerinobotGitProperties;

import com.google.inject.Guice;

public class TillerinobotConfigurationModuleTest {
	@Test
	public void testGitProperties() throws Exception {
		// this file would have been generated by the 
		assumeTrue(getClass().getResourceAsStream("/tillerinobot.git.properties") != null);

		Guice.createInjector(new TillerinobotConfigurationModule()).getInstance(TillerinobotGitProperties.class);
	}
}
